### PR TITLE
ROAD-607: Action Plan should only include approved stories

### LINKED ISSUE #321: Action Plan should only include approved stories
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

**Expected behavior:**

The Action Plan generation should only include `approved` stories.

**Actual behavior:**

The action plan page includes all stories doesn't matter what status are in.
 
**Steps to reproduce:**

How do I achieve this behavior? Use the following format to provide a step-by-step guide:

1. Visit http://localhost:3000/projects/2/action_plan
2. You can see stories with a pending status

**Context and environment:**

Provide any relevant information about your setup (Customize the list accordingly based on what info is relevant to this project)

1. Version of the software the issue is being opened for.
2. Operating System **Linux Mint**
3. Operating System version **21.2**
4. Browser **Google Chrome**
5. Browser version **Version 120.0.6099.224 (Official Build) unknown (64-bit)**
6. Device **Dell XPS**

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by JuanVqz**
### Jira Ticket

Closes #321

### Motivation / Context
Action Plan should only include Approved stories

### QA / Testing Instructions

Visit the action plan page and should only include Approved stories

### Screenshots:

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: spec/models/project_spec.rb [hunk 1]
```diff
@@ -21,17 +21,18 @@
     expect(sub_project2.position).to eq 2
   end
 
-  describe ".with_ordered_descendents" do
+  describe ".sub_projects_with_ordered_stories" do
```
Comment (JuanVqz) [inline spec/models/project_spec.rb:24]: Matching the name with the existing `scope`.
https://github.com/fastruby/points/blob/d0eb2eed881338a83a68a792a68c6c22106eea7c/app/models/project.rb#L16

File: spec/models/story_spec.rb [hunk 2]
```diff
@@ -115,4 +115,13 @@
       end
     end
   end
+
+  describe ".approved" do
+    it "returns only approved stories" do
+      approved_stories = FactoryBot.create_list(:story, 2, :approved)
+      FactoryBot.create_list(:story, 2, :rejected)
+
+      expect(Story.approved).to eq(approved_stories)
```
Comment (JuanVqz) [inline spec/models/story_spec.rb:124]: Creating a scope wasn't needed because it is an `enum` attribute and Rails automagically generates those scopes for you

https://github.com/fastruby/points/blob/d0eb2eed881338a83a68a792a68c6c22106eea7c/app/models/story.rb#L11

File: spec/features/action_plan_generate_spec.rb
Comment (JuanVqz) [inline spec/features/action_plan_generate_spec.rb:1]: Added tasks with `approved`, `pending`, and `rejected`.

**Review by fbuys — APPROVED** [review]

**Review by hmdros — COMMENTED** [review]
@fbuys @JuanVqz 
the one question I have from QAing this is: does locking the project/subproject should change that scoped query?

Right now if I lock the subproject it doesn't affect the outcome of the ActionPlan, should we consider it? 
If we don't want to consider it, this should be good to go.

**Review by hmdros — APPROVED** [review]

**Comment by fbuys** [comment]
> @fbuys @JuanVqz the one question I have from QAing this is: does locking the project/subproject should change that scoped query?
> 
> Right now if I lock the subproject it doesn't affect the outcome of the ActionPlan, should we consider it? If we don't want to consider it, this should be good to go.

The locking feature does not affect the action plan export at all.

**Comment by hmdros** [comment]
> @fbuys @JuanVqz the one question I have from QAing this is: does locking the project/subproject should change that scoped query?
> 
> Right now if I lock the subproject it doesn't affect the outcome of the ActionPlan, should we consider it? If we don't want to consider it, this should be good to go.

Locking a project is usually used to not update project's information. It shouldn't affect the status on stories.
