### PR TITLE
Handle multiple estimations for one user and N+1 queries

### LINKED ISSUE #136: The project's show page does multiple N+1 queries
**Branch/Commit:**

Main branch

**Expected behavior:**

When opening the show action for a project, the number of queries to the db should be minimal:
- 1 query for the project
- 1 query for the stories of that project
- 1 query for all the estimates of the current user

**Actual behavior:**

The code is doing 1 query for the estimate of each story and multiple queries to get the totals for best/worst at the end of the table

So, in a project with 4 stories, it's doing something like:

```
  Project Load (0.1ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2  [["id", 8], ["LIMIT", 1]]
  Story Load (0.2ms)  SELECT "stories".* FROM "stories" WHERE "stories"."project_id" = $1 ORDER BY "stories"."position" ASC, "stories"."created_at" ASC  [["project_id", 8]]
  Estimate Load (0.1ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 17], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 17], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 17], ["user_id", 3], ["LIMIT", 1]]
  Estimate Load (0.1ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 18], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 18], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 18], ["user_id", 3], ["LIMIT", 1]]
  Estimate Load (0.1ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 19], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 19], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 19], ["user_id", 3], ["LIMIT", 1]]
  Estimate Load (0.1ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 20], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 20], ["user_id", 3], ["LIMIT", 1]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2 ORDER BY "estimates"."id" ASC LIMIT $3  [["story_id", 20], ["user_id", 3], ["LIMIT", 1]]
  Story Load (0.1ms)  SELECT "stories".* FROM "stories" WHERE "stories"."project_id" = $1  [["project_id", 8]]
   (0.1ms)  SELECT SUM("estimates"."best_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 17], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."best_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 18], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."best_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 20], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."best_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 19], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."worst_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 17], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."worst_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 18], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."worst_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 20], ["user_id", 3]]
   (0.1ms)  SELECT SUM("estimates"."worst_case_points") FROM "estimates" WHERE "estimates"."story_id" = $1 AND "estimates"."user_id" = $2  [["story_id", 19], ["user_id", 3]]
```

You can see it's doing one query for each story to show the estimates in the row, then it's doing an extra query to fetch the stories for the project (which we already have queries in the second line!) and then it does one SUM query for each story for the best and for the worst case scenarios.

**Steps to reproduce:**

Just create stories on a project and check the logs when you open the show action for that project.

**Delete any information that is not relevant**

We should be able to query the project, the stories of the project, and all the estimates for all those estories for the current user and then use the information already loaded, process it and show estimates in the right places instead of querying them again from the DB.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### LINKED ISSUE #141: Totals in estimations report are incorrect sometimes
**Branch/Commit:**

Main branch.

**Expected behavior:**

The totals at the end of the table for each estimator should add up to the individual numbers listed above

**Actual behavior:**

The totals are sometimes higher than the sum of the numbers listed above

**Steps to reproduce:**

I don't have a clear step by step to reproduce it, but I think it's caused by some estimations not getting deleted when stories are deleted or when re-estimations are done.

But for example, these are the totals for 2 estimators on one of the projects:
254 | 397 | 169 | 295

Copying the table into excel and doing the sum of those number:
164 | 252 | 169 | 295

I'll review the stories of that project later to see what's going on, but I think the problem could be that, from the code, it seems that a story can have multiple estimations from the same user (why is that? is that a bug? the code seems to be expecting that to happen though)

```
  def best_estimate_sum(user)
    estimates.where(user: user).sum(:best_case_points)
  end
```

EDIT: I added #142 to address a bug that should eventually make this not an issue, but this issue should still be fixed by only counting the last estimate for each story for a given user instead of adding all the estimated for each story.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by arielj**
**Description:**

This PR fixes 2 issues. I started working on #141 but some changes were too related to #136.

There's currently a bug that allows estimators to add more than 1 estimate for a given story (#142), even though when that bug gets fixed, we still need to handle old data that's already in the DB and this PR does that.

For 141, I refactored some methods to always get the first estimate by a given user and only counting 1 estimate per user when doing totals and averages.

These changes were closely related to 136 because to optimize the way the refactor works I had to add a bunch of `includes(:estimates)` in some places, which removes the N+` queries.

**How to test/QA:**

You can follow the steps in #142 to generate more than 1 estimate for a user and then you can check in the report that the totals and averages won't match the actual total and average of the table before this fix.

To test #136, you can check the logs when you open a project's show action, now the logs look like:

```
  Project Load (0.1ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Rendered shared/_project_title.html.erb (Duration: 1.6ms | Allocations: 1659)
  Story Load (0.3ms)  SELECT "stories".* FROM "stories" WHERE "stories"."project_id" = $1 ORDER BY position ASC NULLS FIRST, created_at ASC  [["project_id", 4]]
  Estimate Load (0.1ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)  [["story_id", 9], ["story_id", 23], ["story_id", 24], ["story_id", 25], ["story_id", 26], ["story_id", 27], ["story_id", 28], ["story_id", 29], ["story_id", 30], ["story_id", 31], ["story_id", 32]]
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  Story Load (0.1ms)  SELECT "stories".* FROM "stories" WHERE "stories"."project_id" = $1  [["project_id", 4]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)  [["story_id", 9], ["story_id", 23], ["story_id", 24], ["story_id", 25], ["story_id", 26], ["story_id", 27], ["story_id", 28], ["story_id", 29], ["story_id", 30], ["story_id", 31], ["story_id", 32]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  CACHE Story Load (0.0ms)  SELECT "stories".* FROM "stories" WHERE "stories"."project_id" = $1  [["project_id", 4]]
  CACHE Estimate Load (0.0ms)  SELECT "estimates".* FROM "estimates" WHERE "estimates"."story_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)  [["story_id", 9], ["story_id", 23], ["story_id", 24], ["story_id", 25], ["story_id", 26], ["story_id", 27], ["story_id", 28], ["story_id", 29], ["story_id", 30], ["story_id", 31], ["story_id", 32]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
```
with only 3 queries (project, stories, estimate) and some cached queries that are 0.0ms and no N+1

Closes #141 
Closes #136 

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

File: app/models/story.rb [hunk 1]
```diff
@@ -2,33 +2,41 @@ class Story < ApplicationRecord
...
 
   belongs_to :project
-
   has_many :estimates
+  has_many :users, through: :estimates
 
   before_create :add_position
 
-  scope :by_position, -> { order("position ASC NULLS FIRST, created_at ASC") }
+  scope :by_position, -> { order("stories.position ASC NULLS FIRST, stories.created_at ASC") }
```
Comment (arielj) [inline app/models/story.rb:10]: this is needed because using `includes(:estimates)` creates amiguity of which `created_at` column to sort by

File: spec/features/reports_manage_spec.rb [hunk 2]
```diff
@@ -92,5 +92,28 @@
...
+      it "uses the first estimation" do
+        anotherEstimation =
+          FactoryBot.create(:estimate, story: story, user: user,
+            best_case_points: 8,
+            worst_case_points: 13,
+            created_at: 2.minutes.from_now)
+            
+        visit project_report_path(project.id)
+
+        expect(find("tbody tr:first-child td:nth-child(2)")).to have_text "1"
```
Comment (neutrino) [inline spec/features/reports_manage_spec.rb:108]: @arielj : I think, we could group this  with `within` block here.
```
within('tbody tr:first-child') do
    expect(find("td:nth-child(2)")).to have_text "1"
    expect(find("td:nth-child(3)")).to have_text "4"
end
```

File: spec/features/reports_manage_spec.rb [hunk 3]
```diff
@@ -92,5 +92,28 @@
...
+
+    # there's a bug that allows estimators to have more than 1 estimate for a given story
+    # even after that bug gets fixed, we have to be sure we handle old data correctly
+    context "by the same user" do
+      it "uses the first estimation" do
+        anotherEstimation =
+          FactoryBot.create(:estimate, story: story, user: user,
+            best_case_points: 8,
+            worst_case_points: 13,
+            created_at: 2.minutes.from_now)
```
Comment (lubc) [inline spec/features/reports_manage_spec.rb:104]: @arielj hm, It looks a bit weird to me to have a `anotherEstimation` variable here. Maybe it'd be better to move the factory to a `before` block:

```
context "by the same user" do
  before do
    FactoryBot.create(:estimate, story: story, user: user, best_case_points: 8, worst_case_points: 13, created_at: 2.minutes.from_now)
  end

  it "...
```

Comment (arielj) [reply spec/features/reports_manage_spec.rb:104]: personally, I don't like to have a before block for a single test and it looks weird to me xD, but I don't have a strong opinion haha, I'll move it to be a `let` like the rest of the objects that are created in that file

**Review by lubc — APPROVED** [review]

**Comment by lubc** [comment]
@fbuys hey, could you please QA this PR? Thanks!

**Review by fbuys — APPROVED** [review]
Works great!

I checked the logs and noticed that the amount of `estimates` queries reduced to one only with this change ✅

I alos added multiple estimations and noticed that the totals score was wrong, but fixed once the changes from this branch was added ✅

🚀

**Review by neutrino — APPROVED** [review]
